#!/bin/bash

hash="$(echo -n "`date +%s`" | sha256sum | sed "s/-//g" | head -c 8 ; echo )"

git status

#pull so para garantir
git pull origin master

git add .
git status

git commit -m "$hash"

git push origin master

