#!/bin/bash

# 1 - EXTRA - MAURÍCIO
sudo chmod +x repositoriosMauricio
./repositoriosMauricio


# 2 - USER NO SUDO
echo -e "\e[91mInsira o nome do seu usuário no documento aberto, igual a linha destacada:
# User privilege specification
root	ALL=(ALL:ALL) ALL
\e[41m\e[97mUSUARIO	ALL=(ALL:ALL) ALL\e[0m

"
read -n1 -p "Enter para continuar"


export VISUAL="visudo"
export EDITOR="$VISUAL"

sudo -E visudo


# 3 - SUDOEDIT
echo -e "\e[91mSelecione a alternativa referente ao editor VIM \e[0m"
sudo update-alternatives --config editor


# 4 - BASH-COMPLETION
echo "Instalando bash-completion"
sudo apt-get install bash-completion
echo -e "\e[34m\e[1mInsira este código no final do arquivo
if [ -f /etc/bash_completion ]; then
 . /etc/bash_completion
fi
\e[0m"
sudoedit /etc/profile


# 5 - GRUB TIME TO 0
echo -e "\e[91mModifique o tempo de inicialização do GRUB para 0\e[0m

"
read -n1 -p "Enter para abrir arquivo"
sudoedit /etc/default/grub

echo "Atualizando grub"
sudo update-grub


# 6 - ADICIONANDO BACKPORTS
echo 'deb http://deb.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/backports.list


###### EXTRA ######

echo "Creating a Projects folder"
mkdir ~/Projects
