#!/bin/bash

OSVERSION="$(cat /etc/os-release | grep VERSION_ID | grep -oP '"\K[^"\047]+(?=["\047])')"

#APPS GOOGLE
echo "Google key"
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

echo "Google chrome source"
echo 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

echo "Google Music Manager source"
echo 'deb [arch=amd64] https://dl.google.com/linux/musicmanager/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-musicmanager.list


#WINE
echo "Adicionando arquitetura i386 - wine"
sudo dpkg --add-architecture i386

echo "Wine key"
wget -q -O - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -

echo "Wine source"
echo "deb https://dl.winehq.org/wine-builds/debian/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/wine.list


#MEGASYNC
echo "MEGASYNC key"
wget -q -O - https://mega.nz/linux/MEGAsync/Debian_$OSVERSION.0/Release.key | sudo apt-key add -

echo "MEGASYNC source"
echo "deb http://mega.nz/linux/MEGAsync/Debian_$OSVERSION.0/ ./" | sudo tee /etc/apt/sources.list.d/megasync.list


#VIRTUALBOX
echo "Virtualbox key"
wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -

echo "Virtualbox source"
echo "deb https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.org.list
 

#DOCKER

echo "Docker key"
wget -q -O - https://download.docker.com/linux/debian/gpg | sudo apt-key add -

echo "Docker source"
echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list


sudo apt-get update
