#!/bin/bash

echo "Deletando clipboard do KDE"
sudo rm -rf /usr/share/plasma/plasmoids/org.kde.plasma.clipboard

echo "Setando k3b, dolphin, kwrite, konsole como manual"
sudo apt-get install k3b dolphin kwrite konsole

echo "Instalando vlc e clementine"
sudo apt-get install vlc clementine -y

echo "Deletando KAccessible" 
sudo apt-get purge kaccessible -y

echo "Deletando Dragon e Juk"
sudo apt-get purge dragonplayer juk -y

echo "Deletando Thai x terminal"
sudo apt-get purge xiterm+thai -y

echo "Deletando KMail"
sudo apt-get purge kmail -y

echo "Deletando KwalletManager"
sudo apt-get purge kwalletmanager -y

echo "Deletando KAddressBook"
sudo apt-get purge kaddressbook -y

echo "Deletando kopete"
sudo apt-get purge kopete -y

echo "Deletando hugin"
sudo apt-get purge hugin* -y

echo "Deletando korganizer"
sudo apt-get purge korganizer -y

echo "Deletando akregator"
sudo apt-get purge akregator -y

echo "Deletando khmerconverter"
sudo apt-get purge khmerconverter -y

echo "Dando um autoremove nos pacotes não mais necessários"
sudo apt-get autoremove -y
