#!/bin/bash

echo "Deletando clipboard do KDE"
sudo rm -rf /usr/share/plasma/plasmoids/org.kde.plasma.clipboard

echo "Setando k3b, dolphin, kwrite, konsole como manual"
sudo apt-get install k3b dolphin kwrite konsole

echo "Instalando vlc e clementine"
sudo apt-get install vlc clementine -y

echo "Deletando KAccessible" 
sudo apt-get purge kaccessible -y

echo "Deletando Dragon e Juk"
sudo apt-get purge dragonplayer juk -y

echo "Deletando Thai x terminal"
sudo apt-get purge xiterm+thai -y

echo "Dando um autoremove nos pacotes não mais necessários"
sudo apt-get autoremove -y
